"""Build evals/questions.yaml from its three sources and check it.

1. Expert rulings (rulings.py): stratum `expert-ruling`, or `expert-ruling-faq`
   when the answer leans on an official Riot FAQ. Riot's FAQs are part of the
   corpus to be ingested, so those are reported apart from the headline
   number (brief section 5).
2. Version-change questions from evals/drift_candidates.yaml (slice 3), each
   asked twice: once today, expecting the current rule, and once inside the
   window of the latest stale version, expecting that version's rule. The
   second form is what makes date-awareness measurable in both directions.
3. The sampled human review (review.py) adds agreement, not questions.

Every expected ref is checked against data/corpus.json, the committed list of
what was actually ingested. A ruling citing a rule number that does not exist
in v1.4 is reported, never silently dropped.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

import yaml

from rb_errata.labels import rulings as rulings_mod
from rb_errata.labels.rulings import Ruling

QUESTIONS = Path("evals/questions.yaml")
CORPUS = Path("data/corpus.json")
EFFECTIVE = Path("data/effective_dates.json")
# Rulings were checked against v1.4; any date in its window asks the same
# question. A fixed date keeps the set reproducible.
TODAY = date(2026, 10, 1)

HEADER = """\
# GENERATED by `make questions` (rb_errata/labels/build.py). Do not edit by hand:
# change the sources and rebuild.
#
# Licence. Entries with stratum expert-ruling / expert-ruling-faq are adapted from
# Riftbound FAQ by Christian "Near" Ivicevic (github.com/ChristianIvicevic/riftboundfaq,
# commit {commit}), licensed CC BY-SA 4.0. Those entries are distributed under the
# same licence. Rules text belongs to Riot Games and is not included; rule
# references are numbers only.
#
# Strata (report separately, never pooled into one number):
#   expert-ruling      headline set; answers by an experienced rules author
#   expert-ruling-faq  answer leans on an official Riot FAQ, which is in the corpus
#   version-change     written from the rules diff; version_dependent confirmed
"""


@dataclass(frozen=True)
class History:
    """How a v1.4 rule relates to its counterparts in older versions."""

    status: str  # "stable" | "changed" | "new-in-1.4" | "unknown"


def rule_history(versions: dict[str, list[Any]], latest: str) -> dict[str, History]:
    """Per v1.4 rule number: did its text change anywhere in the history?

    Textual change is an upper bound on version dependence: a reworded rule
    can still give the same answer. Confirmed version dependence comes only
    from the version-change stratum, whose answers were checked by reading.
    """
    from rb_errata.ingest.align import align, normalise

    new_rules = versions[latest]
    back = {
        v: {m.new.number: m.old for m in align(rs, new_rules)[0] if m.new is not None}
        for v, rs in versions.items()
        if v != latest
    }
    out: dict[str, History] = {}
    previous = max(back) if back else None
    for r in new_rules:
        if previous is None or r.number not in back[previous]:
            out[r.number] = History("new-in-1.4")
            continue
        olds = [m[r.number] for m in back.values() if r.number in m]
        same = all(normalise(o.text) == normalise(r.text) for o in olds)
        out[r.number] = History("stable" if same else "changed")
    return out


def _windows() -> dict[str, tuple[date, date | None]]:
    rows = json.loads(EFFECTIVE.read_text())
    known = sorted(
        (date.fromisoformat(r["effective"]), r["version"]) for r in rows if r["status"] == "known"
    )
    out: dict[str, tuple[date, date | None]] = {}
    for i, (start, v) in enumerate(known):
        out[v] = (start, known[i + 1][0] if i + 1 < len(known) else None)
    return out


def _version(ref: str) -> str:
    return ref.split("@", 1)[1].split(":", 1)[0]


def ruling_entry(r: Ruling, history: dict[str, History]) -> dict[str, Any]:
    statuses = [history.get(n, History("unknown")).status for n in r.rule_numbers]
    return {
        "id": r.id,
        "question": r.question,
        "as_of": TODAY.isoformat(),
        "expect_sources": [f"core@1.4:{n}" for n in r.rule_numbers],
        # Three states: true / false / null. Nobody has checked by reading
        # whether a ruling's answer differs under older rules, so it is null.
        # First draft set this to "any cited rule's text changed", which came
        # out at 156 of 160: rewording is near-universal and rarely changes an
        # answer, so that figure overstated exactly what the brief asks to
        # report honestly. The measurable part is kept under its real name:
        "version_dependent": None,
        # An older version of at least one cited rule exists AND reads
        # differently. That is the precondition for naive retrieval to return
        # a stale copy (slice 3), not proof that the answer differs.
        "stale_text_exists": "changed" in statuses,
        "provenance": "mined",
        "stratum": "expert-ruling-faq" if r.faq_backed else "expert-ruling",
        "category": r.category,
        "answer_short": r.answer_short,
        "answer": r.answer,
        "cited_rule_history": dict(zip(r.rule_numbers, statuses, strict=True)),
        "source": {
            "url": r.url,
            "authors": r.authors,
            "reviewed_core_rules": r.reviewed_version,
            "created": r.created,
            "licence": "CC BY-SA 4.0",
        },
    }


def drift_entries(windows: dict[str, tuple[date, date | None]]) -> list[dict[str, Any]]:
    from rb_errata.drift import load_candidates

    out = []
    for c in load_candidates():
        base = {
            "provenance": "written",
            "stratum": "version-change",
            "version_dependent": True,
            "change": c.change,
            "source": {"from": "evals/drift_candidates.yaml", "id": c.id},
        }
        current = {"id": f"v-{c.id}-current", "question": c.question, "as_of": c.as_of.isoformat()}
        out.append({**current, "expect_sources": sorted(c.current), **base})
        latest_stale = max(
            {_version(s) for s in c.stale}, key=lambda v: tuple(map(int, v.split(".")))
        )
        start, end = windows[latest_stale]
        assert end is not None, "a stale version always has an end"
        mid = start + (end - start) / 2
        out.append({"id": f"v-{c.id}-v{latest_stale}", "question": c.question,
                    "as_of": mid.isoformat(),
                    "expect_sources": sorted(s for s in c.stale if _version(s) == latest_stale),
                    **base})  # fmt: skip
    return out


def corpus_refs() -> set[str]:
    manifest = json.loads(CORPUS.read_text())
    return {c["source_ref"].split(":")[0] + ":" + r for c in manifest["chunks"] for r in c["refs"]}


def validate(entries: list[dict[str, Any]], known: set[str]) -> list[str]:
    problems = []
    for e in entries:
        missing = [s for s in e["expect_sources"] if s not in known]
        if missing:
            problems.append(f"{e['id']}: cites refs not in the corpus: {missing}")
        if not e["expect_sources"]:
            problems.append(f"{e['id']}: no expected sources")
    return problems


def build(
    clone: Path, versions: dict[str, list[Any]], latest: str
) -> tuple[list[dict[str, Any]], list[str]]:
    rulings = rulings_mod.parse_all(clone)
    history = rule_history(versions, latest)
    entries = [ruling_entry(r, history) for r in rulings] + drift_entries(_windows())
    problems = validate(entries, corpus_refs())
    QUESTIONS.write_text(
        HEADER.format(commit=rulings_mod.COMMIT)
        + yaml.safe_dump(entries, sort_keys=False, allow_unicode=True, width=100)
    )
    return entries, problems
